apiVersion: v1
kind: Service
metadata:
  name: scout
  namespace: scout
  labels:
    app.kubernetes.io/name: scout
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: scout
  ports:
    - name: http
      port: 18447
      targetPort: http
